version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "aws-lambda-express"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wmmz2s0no9h4"
s3_prefix = "aws-lambda-express"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
